/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppHistoricoRouteImport } from './routes/app.historico'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppTarefasRouteImport } from './routes/app.tarefas'
import { Route as AppTarefasIdRouteImport } from './routes/app.tarefas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasRoute = AppTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AppRoute,
} as any)
const AppTarefasIdRoute = AppTarefasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTarefasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/tarefas': typeof AppTarefasRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/tarefas/$id': typeof AppTarefasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/tarefas': typeof AppTarefasRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/tarefas/$id': typeof AppTarefasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/copilot': typeof AppCopilotRoute
  '/app/historico': typeof AppHistoricoRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/tarefas': typeof AppTarefasRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/tarefas/$id': typeof AppTarefasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/copilot'
    | '/app/historico'
    | '/app/perfil'
    | '/app/tarefas'
    | '/app/'
    | '/app/tarefas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/copilot'
    | '/app/historico'
    | '/app/perfil'
    | '/app/tarefas'
    | '/app'
    | '/app/tarefas/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/copilot'
    | '/app/historico'
    | '/app/perfil'
    | '/app/tarefas'
    | '/app/'
    | '/app/tarefas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/historico': {
      id: '/app/historico'
      path: '/historico'
      fullPath: '/app/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas': {
      id: '/app/tarefas'
      path: '/tarefas'
      fullPath: '/app/tarefas'
      preLoaderRoute: typeof AppTarefasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tarefas/$id': {
      id: '/app/tarefas/$id'
      path: '/$id'
      fullPath: '/app/tarefas/$id'
      preLoaderRoute: typeof AppTarefasIdRouteImport
      parentRoute: typeof AppTarefasRoute
    }
  }
}

interface AppTarefasRouteChildren {
  AppTarefasIdRoute: typeof AppTarefasIdRoute
}

const AppTarefasRouteChildren: AppTarefasRouteChildren = {
  AppTarefasIdRoute: AppTarefasIdRoute,
}

const AppTarefasRouteWithChildren = AppTarefasRoute._addFileChildren(
  AppTarefasRouteChildren,
)

interface AppRouteChildren {
  AppCopilotRoute: typeof AppCopilotRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTarefasRoute: typeof AppTarefasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCopilotRoute: AppCopilotRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTarefasRoute: AppTarefasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
